spring:
  application:
    name: zipkin
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
